language: node_js
node_js:
  - "12"
before_install:
  - "sudo apt-get install -y libgnome-keyring-dev libsecret-1-dev"
  - "sudo apt-get install -y xvfb"
# addons:
#   apt:
#     packages:
#       - xvfb

install:
  - export DISPLAY=':99.0'
  # - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &