language: node_js
node_js:
  - "12"
before_install:
  - "sudo apt-get install -y libgnome-keyring-dev libsecret-1-dev"
 

  before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"