dist: xenial
sudo: false

language: node_js
node_js: "12"

cache: yarn

os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - xvfb  

# Workaround for timeout problems when installing packages.
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then scripts/disable_window_defender; fi

script: if [ "$TRAVIS_OS_NAME" = "linux" ]; then xvfb-run yarn test; else yarn test; fi

jobs:
  include:
    - stage: build
      os: linux
      script: "cd packages/main && yarn make"

    - stage: build
      os: osx
      script: "cd packages/main && yarn make"

    - stage: build
      os: windows
      script: "cd packages/main && yarn make"

    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: "cd packages/main && npx semantic-release"
