language: node_js
node_js:
  - "12"
dist: xenial
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - xvfb  
# before_install:
#   - "sudo apt-get install -y libgnome-keyring-dev libsecret-1-dev"
#   - "sudo apt-get install -y xvfb"
script: xvfb-run yarn test