language: node_js
node_js:
  - "12"
dist: xenial
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - xvfb  

script: 
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then yarn test; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then xvfb-run yarn test; fi