dist: xenial
sudo: false

language: node_js
node_js: "12"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  yarn: true
  directories:
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.electron
    - $HOME/.electron-gyp
    - $HOME/.node-gyp
    - $HOME/.npm/_prebuilds

os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - xvfb  

script: if [ "$TRAVIS_OS_NAME" = "linux" ]; then xvfb-run yarn test; else yarn test; fi

jobs:
  include:
    - stage: build
      os: linux
      script: "cd packages/main && yarn make"

    - stage: build
      os: osx
      script: "cd packages/main && yarn make"

    - stage: build
      os: windows
      script: "cd packages/main && yarn make"

    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: "cd packages/main && npx semantic-release"
