language: node_js
node_js:
  - "12"
before_install:
  - "sudo apt-get install -y libgnome-keyring-dev libsecret-1-dev"
  - "sudo apt-get install -y xvfb"

script: xvfb-run make test

  # before_script:
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"