os: linux
dist: xenial

language: node_js
node_js: "12"

cache: yarn

addons:
  apt:
    packages:
      - fakeroot
      - libgnome-keyring-dev
      - libsecret-1-dev
      - xvfb  

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then scripts/disable_window_defender; fi

script: if [ "$TRAVIS_OS_NAME" = "linux" ]; then xvfb-run yarn test; else yarn test; fi

jobs:
  include:
    - stage: build
      os: linux
      script: "cd packages/main && yarn make"

    - stage: build
      os: osx
      script: "cd packages/main && yarn make"

    - stage: build
      os: windows
      env:
        - YARN_GPG=no # avoids GPG subprocess that prevents Travis build from completing
      script: "cd packages/main && yarn make"

    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: "cd packages/main && npx semantic-release"
