language: node_js
node_js:
  - "12"
dist: xenial
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - xvfb  

script: 
  - if os = osx; then yarn test
  - if os = linux; then xvfb-run yarn test