#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

concurrently \
	"cd $DIR/../packages/client && yarn start" \
	"cd $DIR/../packages/main && wait-on http://localhost:3000/ && yarn start"
