#!/bin/bash
#
# Configure Windows Defender so that it does not interfere so severely with
# package downloads from NPM.
#
# This is copied from https://travis-ci.community/t/yarn-network-troubles/333/7

set -e

NODEPATH=$(where.exe node.exe)
PROJECTDIR=$(pwd)
YARNCACHE=$(yarn cache dir)
TEMPDIR=$LOCALAPPDATA\\Temp

powershell Add-MpPreference -ExclusionProcess ${NODEPATH}
powershell Add-MpPreference -ExclusionPath ${YARNCACHE}
powershell Add-MpPreference -ExclusionPath ${PROJECTDIR}
powershell Add-MpPreference -ExclusionPath ${TEMPDIR}
powershell Add-MpPreference -ExclusionPath $LOCALAPPDATA\\electron\\Cache

echo "DisableArchiveScanning..."
powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"

echo "DisableBehaviorMonitoring..."
powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"

echo "DisableRealtimeMonitoring..."
powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"

