#!/bin/bash
#
# We have modified copies of some type definitions from DefinitelyTyped in the
# `types/` directory. These are written in the non-global style, meaning that
# there is no `declare module` wrapping around the definitions. To use this
# style of type definitions they must be put somewhere where TypeScript's module
# resolution algorithm will find them. DefinitelyTyped puts these files in
# `node_modules/@types/`, so we will do the same. But yarn deletes everything in
# `node_modules/` when installing so we cannot keep versioned files in there. So
# we use a `postinstall` hook to symlink directories in `types/` into
# `node_modules/@types/`.

set -e

link_type () {
  local t="$1"
  local l="node_modules/@types/${t##*/}"
  if [[ ! -L $l ]]; then
    ln -s "../../$t" "$l"
  fi
}

for t in types/*; do
  link_type "$t"
done
