#!/bin/bash
#
# We have modified copies of some type definitions from DefinitelyTyped in the
# `types/` directory. These are written in the non-global style, meaning that
# there is no `declare module` wrapping around the definitions. To use this
# style of type definitions they must be put somewhere where TypeScript's module
# resolution algorithm will find them. DefinitelyTyped puts these files in
# `node_modules/@types/`, so we will do the same. But yarn deletes everything in
# `node_modules/` when installing so we cannot keep versioned files in there. So
# we use a `postinstall` hook to symlink directories in `types/` into
# `node_modules/@types/`.

set -e

## Install custom type definitions

link_type () {
  local t="$1"
  local l="node_modules/@types/${t##*/}"
  if [[ ! -L $l ]]; then
    ln -s "../../$t" "$l"
  fi
}

mkdir -p node_modules/@types
for t in types/*; do
  link_type "$t"
done

## Set necessary permissions for the Electron sandbox helper binary

sandbox_helper_bin=packages/main/node_modules/electron/dist/chrome-sandbox

check_sandbox_helper_permissions () {
  user=$(stat -c '%U' $sandbox_helper_bin)
  perms=$(stat -c '%a' $sandbox_helper_bin)
  [[ "$user" == "root" && "$perms" == "4755" ]]
}

set_sandbox_helper_permissions () {
  echo "The Electron sandbox helper binary will now have ownershep set to 'root' with permissions 4755."
  echo "You may be prompted for your sudo password at this point."
  echo
  echo "running: sudo chown root:root $sandbox_helper_bin && chmod 4755 $sandbox_helper_bin"
  sudo chown root:root $sandbox_helper_bin && sudo chmod 4755 $sandbox_helper_bin
}

if [[ "$OSTYPE" == "linux-gnu" && -f $sandbox_helper_bin ]]; then
  check_sandbox_helper_permissions || set_sandbox_helper_permissions
fi
