#!/bin/bash
set -e

for d in packages/main ; do (cd "$d" && eslint src/**/*.ts)
for d in packages/client ; do (cd "$d" && eslint src/**/*.ts)

(cd packages/main && xvfb-run yarn test)
(cd packages/client && xvfb-run yarn test)