#!/bin/bash
set -e

# Make sure that common package is up-to-date
(cd packages/common && yarn build)

if [[ -n "$CI" ]]; then
  # Check that generated code is up-to-date with GraphQL schema and operations
  # files.
  (cd packages/main && yarn codegen)
  (cd packages/client && yarn codegen)
  echo 'Checking for uncommitted changes - if you see changes then run `yarn codegen` and commit updated files.'
  git diff --exit-code
fi

(cd packages/main && eslint src/**/*.ts)
(cd packages/client && eslint src/**/*.{ts,tsx})

(cd packages/main && yarn test)
(cd packages/client && yarn test)
